sonar.host.url=http://localhost:9000
sonar.projectKey=odoo_sale
sonar.projectName=Odoo Sale Models
sonar.projectVersion=1.0
sonar.sources=addons/sale/models
sonar.language=py
sonar.sourceEncoding=UTF-8
